# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170220_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraadhar',
            old_name='aadhar',
            new_name='aadhar_uid',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profession',
            new_name='occupation',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='gender',
            new_name='sex',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='caste',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='category',
            field=models.CharField(choices=[(b'Minority', b'MN'), (b'Other Backward Classes', b'OBC'), (b'Scheduled Tribes', b'ST'), (b'Special Backwar Classes', b'SBC'), (b'Scheduled categorys', b'SC'), (b'General', b'GN')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education_status',
            field=models.CharField(choices=[(b'10th Pass', b'MATRICULATE'), (b'12th Pass', b'INTERMEDIATE'), (b'Masters(2nd) Degree', b'POST GRADUATE'), (b'Bachelors(1st) Degree', b'GRADUATE')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='income_status',
            field=models.CharField(choices=[(b'', b'POOR'), (b'', b'HIGH MIDDLE'), (b'', b'HIGH UPPER'), (b'', b'LOW MIDDLE'), (b'', b'LOW UPPER')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='pin_code',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pan_num',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='useraadhar',
            unique_together=set([('user_profile', 'aadhar_uid')]),
        ),
    ]
