# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 13:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20170221_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovOfficerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('authorised', models.BooleanField(default=True)),
                ('authorization_level', models.CharField(choices=[(b'Mid Level', b'1'), (b'Entry Level', b'0'), (b'Super Level', b'3'), (b'Senior Level', b'2')], max_length=20)),
                ('officer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
