# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_govofficerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='govofficerprofile',
            name='officer',
        ),
        migrations.AlterUniqueTogether(
            name='useraadhar',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='useraadhar',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='userbankdetails',
            name='user_profile',
        ),
        migrations.AlterUniqueTogether(
            name='userphonenumber',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='userphonenumber',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='GovOfficerProfile',
        ),
        migrations.DeleteModel(
            name='UserAadhar',
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
        migrations.DeleteModel(
            name='UserBankDetails',
        ),
        migrations.DeleteModel(
            name='UserPhoneNumber',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
