# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 07:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(default=b'title', max_length=50)),
                ('tag', models.CharField(max_length=25)),
                ('comment', models.TextField()),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
    ]
