# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_delete_totalexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=75, unique=True)),
                ('icon', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='extra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.ExpenseTag'),
        ),
    ]
