# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResouceCollectionAssociation',
            new_name='ResourceCollectionAssociation',
        ),
    ]
