# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20170125_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcecollectionassociation',
            old_name='category',
            new_name='collection',
        ),
    ]
