# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20170125_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='resouces',
            field=models.ManyToManyField(through='resources.ResourceCollectionAssociation', to='resources.Resource'),
        ),
        migrations.AlterField(
            model_name='resourcecollectionassociation',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Collection'),
        ),
        migrations.RemoveField(
            model_name='resourcecollectionassociation',
            name='resource',
        ),
        migrations.AddField(
            model_name='resourcecollectionassociation',
            name='resource',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='resources.Resource'),
            preserve_default=False,
        ),
    ]
