# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20170125_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='resouces',
            new_name='resources',
        ),
    ]
